dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

cache:
directories:
  - $HOME/.m2
script:
- mvn clean compile test package
after_success:
 - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report